name: Setup Python & Install
description: Sets up Python and installs project dependencies.
inputs:
  key:
    description: 'Key for the python cache'
    required: true
  deps:
    description: 'Extra dependency groups (comma separated)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Cache Python packages (Linux)
      uses: actions/cache@v4
      with:
        path: ${{ env.Python3_ROOT_DIR }}/lib/python3.12/site-packages
        key: python-package-${{ inputs.key }}
    - name: Cache downloads (Linux)
      uses: actions/cache@v4
      with:
        path: ~/.cache/tinygrad/downloads/
        key: downloads-cache-${{ inputs.key }}
    - name: Install dependencies
      run: pip install -e ".[${{ inputs.deps }}]"  --extra-index-url https://download.pytorch.org/whl/cpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/