name: Run process replay tests
description: Verify process replay compared to master
runs:
  using: "composite"
  steps:
    - name: Run process replay tests
      shell: bash
      run: |
        export PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
        export COMMIT_MESSAGE=$(git show -s --format=%B ${{ github.event.pull_request.head.sha }})
        cp test/external/process_replay/process_replay.py ./process_replay.py && git fetch origin master && git -c advice.detachedHead=false checkout origin/master && PYTHONPATH=. python3 process_replay.py
    - name: Restore PR branch
      shell: bash
      run: git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}