from tinygrad.dtype import PtrDType, dtypes, AddrSpace, truncate, DType
from tinygrad.helpers import Target
from tinygrad.renderer.amd.dsl import InsOp
from tinygrad.uop import GroupOp
from tinygrad.uop.ops import Ops, UOp, UPat, PatternMatcher, ParamArg
from tinygrad.renderer.isa import ISARenderer, IselContext, Register, regs, reg
import tinygrad.runtime.autogen.amd.rdna3.ins as RDNA3Ops
from dataclasses import dataclass, field
import itertools

# NOTE: wavefront size is 32, use exec_lo
VGPRS = tuple(Register(f"v{i}", i) for i in range(256))
SGPRS = tuple(Register(f"s{i}", i) for i in range(106))
KERNARG_PTR, WGIDS, WIIDS = tuple(SGPRS[:2]), tuple(SGPRS[2:5]), (VGPRS[0],) # reserved for abi
GP_SGPRS, GP_VGPRS = tuple(SGPRS[5:]), tuple(VGPRS[1:])
VCC, EXEC = Register("vcc", 0), Register("exec_lo", 0)

lane_ctr = itertools.count()
def def_reg(dt, reg:Register|tuple[Register,...]): return UOp.placeholder((1,), dt, next(lane_ctr), AddrSpace.REG).replace(tag=(reg,) if isinstance(reg,Register) else reg)

kernarg_ptr = (def_reg(dtypes.uint32, KERNARG_PTR[0]), def_reg(dtypes.uint32, KERNARG_PTR[1]))
execop = def_reg(dtypes.uint32, EXEC)
lidop = def_reg(dtypes.uint32, WIIDS[0])

spill_ptr = UOp.placeholder((1,), dtypes.uint32, next(lane_ctr), AddrSpace.LOCAL)

def const(dt, v:int) -> UOp: return UOp.const(dt,truncate[dt](v)).rtag()
def is_vgpr(x:UOp) -> bool: return x.tag is not None and x.tag != True and x.tag != GP_SGPRS and x.tag[0].cons[0].name[0] == "v"
# TODO: Handle 64 bit inputs
def to_vgpr(ctx, x:UOp) -> UOp:
  # NOTE: handle sgpr?
  if x.op is Ops.CONST: # is 128 bit consts a thing??
    if x.dtype.itemsize == 8:
      # NOTE: need underpromo dict, just assume uint for now
      lo, hi = const(dtypes.uint32,x.arg), const(dtypes.uint32, x.arg >> 32)
      return to_vgpr(ctx, UOp(Ops.STACK, src=(lo,hi)))
    else: return x.ins(RDNA3Ops.v_mov_b32_e32, src=(x,))
  if x.op is Ops.STACK: return UOp.group(*[u.ins(RDNA3Ops.v_mov_b32_e32, tag=(vr,), src=(u,)) for vr, u in zip(ctx.vreg((GP_VGPRS,len(x.src))), x.src)]) 
  return x
def const_vgpr(ctx, dt, v:int) -> UOp: return to_vgpr(ctx, const(dt, v))

def alloc_vregs(ctx:IselContext, x:UOp) -> UOp|None:
  # real registers
  if x.op is Ops.BUFFER and x.addrspace is not AddrSpace.REG: return None
  # no register definition
  if x.dtype is dtypes.void: return None
  # already allocated vregs
  # NOTE: this is getting shitty, whats the heuristic for cons vs group of registers?
  if isinstance(x.tag, tuple):
    assert x.tag, f"got empty tuple for op: {x.op}, {x.arg}"
  if isinstance(x.tag, tuple) and isinstance(x.tag[0], Register) and x.tag[0]._cons: return None # how can this receive an empty tuple???
  # allocate vreg definitions
  defs = []
  # don't generally allocate to SGPRS, only works wave uniform possible future optim
  # if x.op is Ops.END: defs = [ctx.vreg(GP_SGPRS)] # alloc gate mask
  # TODO: allocatate vgpr / sgpr based on op group (x.arg.func)
  # - should almost never need to manually call ctx.vreg
  # - control flow allocations should also be handled here?
  if isinstance(x.tag, tuple):
    vr = ctx.vreg(x.tag)
    defs = [vr] if isinstance(vr, Register) else [*vr]
  else:
    n = x.dtype.itemsize // 4
    defs = [ctx.vreg(GP_VGPRS)] if n == 1 else ctx.vreg((GP_VGPRS,n))
  return x.replace(tag=tuple(defs))

# https://llvm.org/docs/AMDGPUUsage.html#initial-kernel-execution-state
# TODO: batch param loading? ex. s_load_b128
def abi(ctx:IselContext, x:UOp) -> UOp|None:
  i = ctx.func_args.index(x)
  if x.op is Ops.SPECIAL: # maintain src edge?
    dim = int(x.arg[-1])
    if x.arg[0] == 'g': return UOp(Ops.INS, dtype=dtypes.uint32, arg=RDNA3Ops.v_mov_b32_e32, src=(def_reg(dtypes.uint32, WGIDS[dim]),))
    else: return x.ins(RDNA3Ops.v_bfe_u32, dtype=dtypes.uint32, src=(lidop, const(dtypes.uint32, 10 * dim), const(dtypes.uint32, 10)))
  offs = sum(8 if u.op == Ops.PARAM else 4 for u in ctx.func_args[:i])
  # if AddrSpace is ALU auto load into vgpr??
  if x.addrspace is AddrSpace.ALU:
    val = x.ins(RDNA3Ops.s_load_b32, src=kernarg_ptr + (const(dtypes.uint32, offs),), tag=(ctx.vreg(GP_SGPRS),))
    return UOp(Ops.INS, arg=RDNA3Ops.v_mov_b32_e32, dtype=x.dtype, src=(val,))
  return x.ins(RDNA3Ops.s_load_b64, src=kernarg_ptr + (const(dtypes.uint32, offs),), tag=ctx.vreg((GP_SGPRS, 2)))

dts = dtypes.ints + (dtypes.bool, dtypes.float16, dtypes.float32, dtypes.float64)
dt_16bit = tuple(dt.vec(l) for dt in dts for l in [2,1] if l*dt.itemsize == 2)
dt_32bit = tuple(dt.vec(l) for dt in dts for l in [4,2,1] if l*dt.itemsize == 4)
dt_64bit = tuple(dt.vec(l) for dt in dts for l in [8,4,2,1] if l*dt.itemsize == 8)
dt_128bit = tuple(dt.vec(l) for dt in dts for l in [16,8,4,2,1] if l*dt.itemsize == 16)

# make these autogenerated with string matching and valid type tuples
V_ADD =   { dtypes.float16:RDNA3Ops.v_add_f16_e32,  dtypes.float32:RDNA3Ops.v_add_f32_e32,  dtypes.float64:RDNA3Ops.v_add_f64,   dtypes.int32:RDNA3Ops.v_add_nc_i32,       dtypes.uint32:RDNA3Ops.v_add_nc_u32_e32,  }
V_SUB =   { dtypes.float16:RDNA3Ops.v_sub_f16_e32,  dtypes.float32:RDNA3Ops.v_sub_f32_e32,  dtypes.int32:RDNA3Ops.v_sub_nc_i32,  dtypes.uint32:RDNA3Ops.v_sub_nc_u32_e32,  }
V_MUL =   { dtypes.float16:RDNA3Ops.v_mul_f16_e32,  dtypes.float32:RDNA3Ops.v_mul_f32_e32,  dtypes.float64:RDNA3Ops.v_mul_f64,   dtypes.int32:RDNA3Ops.v_mul_i32_i24_e32,  dtypes.uint32:RDNA3Ops.v_mul_lo_u32 }
V_SQRT =  { dtypes.float16:RDNA3Ops.v_sqrt_f16_e32, dtypes.float32:RDNA3Ops.v_sqrt_f32_e32, dtypes.float64:RDNA3Ops.v_sqrt_f64_e32  }
V_LOG =   { dtypes.float16:RDNA3Ops.v_log_f16_e32,  dtypes.float32:RDNA3Ops.v_log_f32_e32 }
V_EXP =   { dtypes.float16:RDNA3Ops.v_exp_f16_e32,  dtypes.float32:RDNA3Ops.v_exp_f32_e32 }
V_MAX =   { dtypes.float16:RDNA3Ops.v_max_f16_e32,  dtypes.float32:RDNA3Ops.v_max_f32_e32,  dtypes.uint16:RDNA3Ops.v_max_u16,     dtypes.int16:RDNA3Ops.v_max_i16,          dtypes.uint32:RDNA3Ops.v_max_u32_e32,
              dtypes.int32:RDNA3Ops.v_max_i32_e32}
V_RCP =   { dtypes.float16:RDNA3Ops.v_rcp_f16_e32,  dtypes.float32:RDNA3Ops.v_rcp_f32_e32,  dtypes.float64:RDNA3Ops.v_rcp_f64_e32   }
V_SIN =   { dtypes.float16:RDNA3Ops.v_sin_f16_e32,  dtypes.float32:RDNA3Ops.v_sin_f32_e32 }
V_TRUNC = { dtypes.float16:RDNA3Ops.v_trunc_f16_e32,dtypes.float32:RDNA3Ops.v_trunc_f32_e32,dtypes.float64:RDNA3Ops.v_trunc_f64_e32 }
V_FMA =   { dtypes.float16:RDNA3Ops.v_fma_f16,      dtypes.float32:RDNA3Ops.v_fma_f32,      dtypes.float64:RDNA3Ops.v_fma_f64       }
V_CMPLT = { dtypes.float16:RDNA3Ops.v_cmp_lt_f16_e64, dtypes.float32:RDNA3Ops.v_cmp_lt_f32_e64, dtypes.float64:RDNA3Ops.v_cmp_lt_f64_e64, dtypes.uint32:RDNA3Ops.v_cmp_lt_u32_e64,
  dtypes.int32:RDNA3Ops.v_cmp_lt_i32_e64, dtypes.int16:RDNA3Ops.v_cmp_lt_i16_e64, dtypes.uint16:RDNA3Ops.v_cmp_lt_u16_e64 }
V_CMPGT = { dtypes.float16:RDNA3Ops.v_cmp_gt_f16_e64, dtypes.float32:RDNA3Ops.v_cmp_gt_f32_e64, dtypes.float64:RDNA3Ops.v_cmp_gt_f64_e64, dtypes.uint32:RDNA3Ops.v_cmp_gt_u32_e64,
  dtypes.int32:RDNA3Ops.v_cmp_gt_i32_e64, dtypes.int16:RDNA3Ops.v_cmp_gt_i16_e64, dtypes.uint16:RDNA3Ops.v_cmp_gt_u16_e64 }
V_CMPEQ = { dtypes.float16:RDNA3Ops.v_cmp_eq_f16_e64, dtypes.float32:RDNA3Ops.v_cmp_eq_f32_e64, dtypes.float64:RDNA3Ops.v_cmp_eq_f64_e64, dtypes.uint16:RDNA3Ops.v_cmp_eq_u16_e64, dtypes.uint32:RDNA3Ops.v_cmp_eq_u32_e64, dtypes.int16:RDNA3Ops.v_cmp_eq_i16_e64, dtypes.int32:RDNA3Ops.v_cmp_eq_i32_e64 }
V_CMPNE = { dtypes.float16:RDNA3Ops.v_cmp_neq_f16_e64,dtypes.float32:RDNA3Ops.v_cmp_neq_f32_e64,dtypes.float64:RDNA3Ops.v_cmp_neq_f64_e64, dtypes.uint32:RDNA3Ops.v_cmp_ne_u32_e64,
  dtypes.int32:RDNA3Ops.v_cmp_ne_i32_e64, dtypes.int16:RDNA3Ops.v_cmp_ne_i16_e64, dtypes.uint16:RDNA3Ops.v_cmp_ne_u16_e64 }

_isa_typref = { dtypes.int32:"i32", dtypes.uint32:"u32", dtypes.float32:"f32", dtypes.float64:"f64", dtypes.float16:"f16", dtypes.int16:"i16", dtypes.uint16:"u16", dtypes.uint64:"u64", }
def _build_cvt_table():
  _valid_casts = {
      dtypes.float64    : (dtypes.int32, dtypes.float32, dtypes.uint32),
      dtypes.int32      : (dtypes.float64, dtypes.float32),
      dtypes.uint32     : (dtypes.float32, dtypes.float64),
      dtypes.float32    : (dtypes.float64, dtypes.uint32, dtypes.int32, dtypes.float64),
      dtypes.float16    : (dtypes.float32,),
  }
  return { src : { targ: getattr(RDNA3Ops, f"v_cvt_{_isa_typref[targ]}_{_isa_typref[src]}_e32") for targ in targets } for src,targets in _valid_casts.items() }
V_CVT = _build_cvt_table()

def _vop3(ctx, x:UOp):
  lits = [i for i,s in enumerate(x.src) if s.op is Ops.CONST]
  if len(lits) <= 1: return x
  new = list(x.src)
  for i in lits[1:]: new[i]=to_vgpr(ctx, new[i])
  return x.replace(src=tuple(new))

def _vop2(ctx, x:UOp):
  # def _isvgpr(u:UOp): return (r := reg(u)) is not None and isinstance(r, Register) and r.cons[0].name[0] == "v"
  def _isconst(u:UOp): return u.op is Ops.CONST
  if not _isconst(x.src[1]): return x
  rest = x.src[2:] if len(x.src) > 2 else ()
  non_commutative = x.arg in (RDNA3Ops.v_lshlrev_b32_e32, RDNA3Ops.v_lshrrev_b32_e32) # NOTE: add more
  if not non_commutative and not _isconst(x.src[0]): 
    return x.replace(src=(x.src[1], x.src[0]) + rest)
  return x.replace(src=(x.src[0], to_vgpr(ctx, x.src[1])) + rest)

def cmp(ctx, x:UOp):
  rlz = []
  # NOTE: maybe add this functionality to to_vgpr? (bool const + cmp output handling, realize as vgpr per lane result)
  # NOTE: also maybe add this to pre_isel?
  for u in x.src: # convert cmp outputs and const bools to vgpr
    if u.dtype is dtypes.bool:
      if u.op is Ops.CONST: rlz.append(const(dtypes.uint32, 1) if u.arg else const(dtypes.uint32,0))
      else: rlz.append(u.where(const(dtypes.uint32,1), const(dtypes.uint32,0)))
    else: rlz.append(u)
  x = x.replace(src=tuple(rlz))
  dt = x.src[0].dtype.scalar()
  if x.op is Ops.CMPLT: ins = V_CMPLT[dt]
  elif x.op is Ops.CMPEQ: ins = V_CMPEQ[dt]
  elif x.op is Ops.CMPNE: ins = V_CMPNE[dt]
  else: ins = V_CMPGT[dt]
  # else: raise NotImplementedError("comparison type instruction dne")
  return x.ins(ins, tag=GP_SGPRS)
  # return _vop2(ctx, x.ins(ins, tag=GP_SGPRS))

# NOTE: ISA spec 11.2
# GLOBAL_ADDR = SGPR_u64 + VGPR_OFFS_U32 + IMMOFFS_u16
def fold_global(ctx, base:UOp, idx:UOp): # (saddr, voff, ioffs)
  # TODO: handle offseting cleanly, ensure 13 bit imoff doesnt overflow
  disp_scale = base.dtype.itemsize if base.op in {Ops.PARAM, Ops.BUFFER, Ops.AFTER} else 1
  shft = to_vgpr(ctx, const(dtypes.int, disp_scale.bit_length() - 1))
  if idx.op is Ops.CONST:
    return (idx.ins(RDNA3Ops.v_mov_b32_e32, src=(const(dtypes.int, idx.arg * disp_scale),)), base, const(dtypes.int16, 0))
  # if idx.op is Ops.ADD and idx.src[1].op is Ops.CONST: return (idx.src[0] << shft, base, const(dtypes.int16, idx.src[1].arg * disp_scale))
  return (idx << shft, base, const(dtypes.int16, 0))

# LDS_ADDR = VGPR_ADDR_u32 + imm_byte_offset_u16
# base doesn't hold a ptr for local addrspace
# NOTE: keep base in src to maintain graph dependencies?
def fold_lds(ctx, base:UOp, idx:UOp): # (vaddr, ioffs) 
  scale = base.dtype.itemsize if base.op in {Ops.PARAM, Ops.BUFFER, Ops.AFTER} else 1
  if idx.op is Ops.CONST: return (idx.ins(RDNA3Ops.v_mov_b32_e32, src=(const(dtypes.uint32,0),)), idx.arg * scale, base)
  if idx.op is Ops.ADD and idx.src[1].op is Ops.CONST: return (idx.src[0].cast(dtypes.uint32), idx.src[1].arg * scale, base)
  shft = to_vgpr(ctx, const(dtypes.uint32, scale.bit_length() - 1))
  return (idx.cast(dtypes.uint32) << shft, const(dtypes.uint16, 0), base)

# TODO: handle 16 bit loads?
def fold_address(ctx, x:UOp): return fold_lds(ctx, *x.src[:2]) if x.addrspace is AddrSpace.LOCAL else fold_global(ctx, *x.src[:2])
def _insspace(gl,x): return gl[1] if x.addrspace is AddrSpace.LOCAL else gl[0]

def load(ctx, addr:UOp, x:UOp, gate:UOp|None = None, alt:UOp|None = None):
  alt, gate = x.src[1:] if len(x.src) > 1 else (None,None)
  base, idx = addr.src[:2]
  def _gate(o:UOp): return o.replace(src=(to_vgpr(ctx, alt),) + o.src  + (gate,def_reg(dtypes.uint32,GP_SGPRS))) if gate is not None else o
  if base.addrspace is AddrSpace.REG:
    return _gate(x.ins(RDNA3Ops.v_mov_b32_e32, dtype=addr.src[0].dtype, src=(addr.src[0],)))
  imap = {
    1 : (RDNA3Ops.global_load_b32,RDNA3Ops.ds_load_b32),
    2 : (RDNA3Ops.global_load_b64,RDNA3Ops.ds_load_b64),
    4 : (RDNA3Ops.global_load_b128,RDNA3Ops.ds_load_b128),
  }
  n = addr.src[-1].arg if addr.op is Ops.SHRINK else 1
  nregs = (n * x.dtype.itemsize+3)//4
  return _gate(x.ins(_insspace(imap[nregs],base), src=fold_address(ctx, addr), tag=GP_VGPRS if nregs == 1 else (GP_VGPRS, nregs)))

def store(ctx, addr:UOp, x:UOp):
  val, gate = x.src[1], x.src[2] if len(x.src) > 2 else None
  base, idx = addr.src[:2]
  def _gate(o:UOp): return o.replace(src=o.src + (gate,def_reg(dtypes.uint32,GP_SGPRS))) if gate is not None else o
  n = len(val.src) if val.op is Ops.STACK else 1
  if base.addrspace is AddrSpace.REG:
    # how to guarantee its stored in the same reg as buf/base??
    return _gate(UOp(Ops.INS, arg=RDNA3Ops.v_mov_b32_e32, src=(base,to_vgpr(ctx,val))).rtag()) # two address op?
  nregs = (n*val.dtype.itemsize+3)//4
  imap = {
    1:(RDNA3Ops.global_store_b32,RDNA3Ops.ds_store_b32),
    2:(RDNA3Ops.global_store_b64,RDNA3Ops.ds_store_b64),
    4:(RDNA3Ops.global_store_b128,RDNA3Ops.ds_store_b128)
  }
  return _gate(UOp(Ops.INS, arg=_insspace(imap[nregs],base), dtype=dtypes.void, src=fold_address(ctx, addr) + (to_vgpr(ctx,val),)))

# TODO: b64 -> b64
def cvt(ctx, y:UOp, x:UOp):
  def _needcast(x:DType, y:DType): return not (_isa_typref[x][0] == _isa_typref[y][0])
  if x.dtype in (dtypes.uint64, dtypes.int64) and y.dtype.itemsize == 4: # b32 -> b64
    targ = dtypes.uint32 if dtypes.is_unsigned(x.dtype) else dtypes.int32
    lo = y.ins(V_CVT[y.dtype][targ]) if _needcast(y.dtype, targ) else y
    return to_vgpr(ctx, UOp(Ops.STACK, src=(y, const(targ, 0))))
  elif y.dtype.itemsize == 8 and x.dtype.itemsize == 4 and y.dtype is not dtypes.float64: # b64 -> b32
    src = dtypes.uint32 if dtypes.is_unsigned(y.dtype) else dtypes.int32
    if _needcast(src, x.dtype): return x.ins(V_CVT[src][x.dtype], src=(y.gep(0),))
    else: return y.gep(0)
  return x.ins(V_CVT[y.dtype][x.dtype])

# -- complex alu --
def add64(ctx, x:UOp):
  if dtypes.is_float(x.dtype): return x.ins(V_ADD[x.dtype]) # f64 add is native
  a1, a2 = x.ins(RDNA3Ops.v_add_co_u32), x.ins(RDNA3Ops.v_add_co_ci_u32)
  return a2.after(a1)

# TODO: signed
def mul64(ctx, x:UOp):
  a, b = x.src
  p1 = UOp(Ops.INS, arg=RDNA3Ops.v_mad_u64_u32, dtype=dtypes.uint64, src=(a.gep(0), b.gep(0), const(dtypes.uint64,0)))
  p2 = UOp(Ops.INS, arg=RDNA3Ops.v_mad_u64_u32, dtype=dtypes.uint64, src=(a.gep(1), b.gep(0), p1))
  return UOp(Ops.INS, arg=RDNA3Ops.v_mad_u64_u32, dtype=dtypes.uint64, src=(a.gep(0), b.gep(1), p2))

def bitwise64(ctx, x:UOp, ins):
  a, b = x.src
  lo, hi = UOp(Ops.INS, dtypes.uint32, arg=ins, src=(a.gep(0), b.gep(0))), UOp(Ops.INS, dtypes.uint32, arg=ins, src=(a.gep(1), b.gep(1)))
  return UOp.group(lo,hi)

# TODO: handle 16/64 bit semantics
def alu(ctx, x:UOp):
  dpreciz = x.dtype.itemsize == 8
  ins = None
  if len(x.src) == 1:
    if x.op is Ops.SQRT: ins = V_SQRT[x.dtype]
    elif x.op is Ops.LOG2: ins = V_LOG[x.dtype]
    elif x.op is Ops.EXP2: ins = V_EXP[x.dtype]
    elif x.op is Ops.SIN: ins = V_SIN[x.dtype]
    elif x.op is Ops.TRUNC: ins = V_TRUNC[x.dtype]
    elif x.op is Ops.RECIPROCAL: ins = V_RCP[x.dtype]
  else: 
    a,b = x.src
    def _bitwise(ins): return bitwise64(ctx, x, ins) if dpreciz else _vop2(ctx, x.ins(ins))
    # how to handle boolean dtype?
    # ex. AND between 2 bools outputting a bool, should the be an salu op?
    # - cmp outputs are automatically sgprs
    # NOTE: booleans should be natively represented as vcc/scc
    if x.op is Ops.ADD: # TODO: handle signed?
      if dpreciz: return add64(x)
      ins = V_ADD[x.dtype]
    elif x.op is Ops.MUL:
      if dpreciz: return mul64(ctx,x)
      ins = V_MUL[x.dtype]
    elif x.op is Ops.AND: return _bitwise(RDNA3Ops.v_and_b32_e32)
    elif x.op is Ops.OR: return _bitwise(RDNA3Ops.v_or_b32_e32)
    elif x.op is Ops.XOR: return _bitwise(RDNA3Ops.v_xor_b32_e32)
    elif x.op is Ops.SHL:
      x = x.replace(src=x.src[::-1])
      ins = RDNA3Ops.v_lshlrev_b64 if dpreciz else RDNA3Ops.v_lshlrev_b32_e32 
    elif x.op is Ops.SHR:
      x = x.replace(src=x.src[::-1])
      ins = RDNA3Ops.v_lshrrev_b64 if dpreciz else RDNA3Ops.v_lshrrev_b32_e32
  if ins is None:
    raise NotImplementedError(f"alu optype not implemented. op={x.op}, is_unary={len(x.src)==1}")
  return x.ins(ins) if len(x.src) == 1 else _vop2(ctx, x.ins(ins))

# cdiv of int types needs to be converted to float then cast back after ceil op
# - we need to cast to float version of this bitwidth..., start with just 32
def cdiv(x:UOp):
  a,b = [u.cast(dtypes.float32) for u in x.src]
  c = UOp(Ops.INS, dtypes.float32, arg=RDNA3Ops.v_ceil_f32_e32, src=(a.div(b),))
  return c.cast(x.dtype)

pre_isel_matcher = PatternMatcher([
  # cast to ptr is noop
  (UPat.var("y").cast(name="x"), lambda y,x: y if isinstance(x.dtype, PtrDType) or y.dtype == dtypes.void else None),
  # bitcast is noop?
  (UPat.var("y").bitcast().named("x"), lambda y,x: y),
  # NOTE: casting comparison output to float should be treated as a where pred ? 0.0 : 1.0
  (UPat.var("y", dtype=dtypes.bool).cast(name="x"), lambda y,x: y.where(const(x.dtype, 1), const(x.dtype, 0))),
])

def prep_range(ctx, bnd:UOp, x:UOp):
  if x.dtype is dtypes.uint32: return None # this is a shit predicate, maybe utilize ctx
  mask = def_reg(dtypes.uint32, GP_SGPRS)
  return x.replace(src=(bnd,mask)).replace(dtype=dtypes.uint32)

def prep_end(ctx, x:UOp, rng:UOp):
  if not (len(x.src) == 2 and rng.dtype is dtypes.uint32): return None
  one = const_vgpr(ctx,dtypes.uint32,1)
  mask, bnd = rng.src[-1], to_vgpr(ctx, rng.src[0])
  return x.replace(src=x.src + (bnd,one,mask))

# NOTE: maybe add the range exec mask to end src in pre-regalloc?
isel_matcher = PatternMatcher([
  # control flow
  (UPat(Ops.RANGE, src=(UPat.var("bnd"),), allow_any_len=True, name="x"), prep_range),
  (UPat(Ops.END, src=(UPat(), UPat.var("rng")), name="x"), prep_end),
  # noop
  (UPat.var("a").cast(name="x"), lambda a,x: a if a.dtype == x.dtype else None),
  # rtag every const, masks tag type as non Register to ensure it doesn't get treated as one
  (UPat.cvar("x"), lambda x: x.rtag() if not x.tag else None),
  # function abi
  (UPat((Ops.SPECIAL, Ops.PARAM), name="x"), abi),
  # TODO: add fma/mad fuse detection to alu()
  # fused multiply add, use FMAC in the future?
  ((UPat(Ops.MUL, dtype=dtypes.floats, name="a") + UPat.var("b")).named("x"), lambda ctx,a,b,x: _vop3(ctx, x.ins(V_FMA[a.dtype], src=a.src + (b,)))),
  # cast
  (UPat.var("y", dtypes.int).cast(dtypes.uint, name="x"), lambda y,x: y), # noop?
  (UPat.var("y").cast(name="x"), cvt),
  # note: *_e64 cmp and cndmask encoding allows for storage/usage of VCC as SGPR
  (UPat.var("m").where(UPat.var("a", dtype=dt_32bit), UPat().var("b")).named("x"), lambda ctx,m,a,b,x: _vop3(ctx, x.ins(RDNA3Ops.v_cndmask_b32_e64, src=(b,a,cmp(ctx,m))))),
  # cmp shouldn't always be materialized to sgpr, only for where
  (UPat(GroupOp.Comparison, dtypes.bool, name="x"), cmp),
  # mem ops
  (UPat((Ops.INDEX, Ops.SHRINK), name="addr").store(allow_any_len=True, name="x"), store),
  (UPat((Ops.INDEX, Ops.SHRINK), name="addr").load(allow_any_len=True, name="x"), load),
  # unified alu experiment
  (UPat(Ops.CDIV, name="x"), cdiv),
  (UPat(Ops.CMOD, src=(UPat.var("a"), UPat.var("b"))), lambda a,b: a - b * a.alu(Ops.CDIV, b)), # hack from x86
  (UPat(GroupOp.Binary|GroupOp.Unary, name="x"), alu),
  # barrier
  (UPat(Ops.BARRIER, name="x"), lambda x: x.ins(RDNA3Ops.s_barrier)),
  # allocate virtual registers
  (UPat((Ops.INS, Ops.BUFFER, Ops.RANGE), name="x"), alloc_vregs),
])

# --- control flow ---
def restoreexec(mask:UOp) -> UOp: return UOp(Ops.INS, arg=RDNA3Ops.s_or_b32, src=(execop,mask), tag=(EXEC,))
def label(ctx, name:str) -> UOp: return UOp(Ops.INS, arg=RDNA3Ops.s_nop, tag=name)

# TODO: dont use string comparisons, have a clear load/store spec? operands?
def lower_gated(x:UOp):
  if "load" in x.arg.opc and len(x.src) > 3: # gated load
    save = x.src[-1].ins(RDNA3Ops.s_and_saveexec_b32, src=(x.src[-2],))
    return x.src[0], [x.src[0], save, x.replace(src=x.src[1:-2]), restoreexec(x.src[-1])]
  if "store" in x.arg.opc and len(x.src) > 4: # gated store 
    branch = x.src[-1].ins(RDNA3Ops.s_and_saveexec_b32, src=(x.src[-2],))
    return branch, [branch, x.replace(src=x.src[:-2]), restoreexec(x.src[-1])]
  return None

# https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU/SILowerControlFlow.cpp#L423
def lower_range(ctx, x:UOp):
  loop_label = "_".join(str(i) for i in x.arg[:-1])
  acc = x.ins(RDNA3Ops.v_mov_b32_e32, src=(const(dtypes.uint32,0),))
  mask = x.src[-1].ins(RDNA3Ops.s_mov_b32, src=(execop,))
  ctx.loop_label[acc] = loop_label
  lbl = label(ctx, f".LOOP_{loop_label}")
  return acc, [acc, mask, lbl]

def lower_end(ctx, x:UOp):
  gate = UOp(Ops.INS, arg=RDNA3Ops.v_cmpx_lt_u32_e64, src=(x.src[1], x.src[-3]), tag=(EXEC,))
  inc = x.src[1].ins(RDNA3Ops.v_add_nc_u32_e32, src=(x.src[1], x.src[-2]))
  loop = UOp(Ops.INS, arg=RDNA3Ops.s_cbranch_execnz, tag=f".LOOP_{ctx.loop_label[x.src[1]]}")
  return inc, [inc, gate, loop, restoreexec(x.src[-1])]

post_regalloc_matcher = PatternMatcher([
  (UPat(Ops.SINK, name="x"), lambda x: (x, [x.ins(RDNA3Ops.s_endpgm)])),
  (UPat(Ops.INS, name="x"), lambda x: (x,[]) if x.arg is RDNA3Ops.s_nop else None),
  (UPat(Ops.RANGE, name="x"), lower_range),
  (UPat(Ops.END, name="x"), lower_end),
  (UPat(Ops.INS, name="x"), lower_gated),
])

# NOTE: maybe just make my register viewing another rewrite??
def encode(ctx, x:UOp):
  if x.arg in [RDNA3Ops.s_nop, RDNA3Ops.s_endpgm]: return x.replace(arg=x.arg())
  import tinygrad.renderer.amd.dsl as dsl
  def _route(r:Register):
    dmap = { "vcc" : dsl.VCC, "exec_lo" : dsl.EXEC_LO, "v" : dsl.v, "s" : dsl.s  } 
    return dmap[r.name] if r.name in dmap else dmap[r.name[0]]
  def _immorreg(x:UOp): return x.arg if x.op == Ops.CONST else _fuse(regs(x))
  def _fuse(rr:tuple[Register,...]):
    r = _route(rr[0])
    return r[rr[0].index:rr[0].index+len(rr)-1] if len(rr) > 1 else r[rr[0].index]
  enc, group, opc, oprs = x.arg, x.arg.func, x.arg.opc, x.src

  if ctx.is_two_address(x):
    x = x.replace(tag=regs(x.src[0]))
    oprs = oprs[1:]

  # NOTE: hacky fixes, find cleaner way to conform to isa
  kw = args = None
  if group is RDNA3Ops.SMEM:
    kw = dict(sdata=_fuse(regs(x)), sbase=_fuse(tuple(u.tag[0] for u in oprs[:-1])), soffset=dsl.NULL, offset=oprs[-1].arg)
  elif group is RDNA3Ops.GLOBAL:
    kw = dict(addr=_immorreg(oprs[0]), saddr=_fuse(regs(oprs[1])), offset=_immorreg(oprs[2]))
    if reg(x) is None: kw["data"]=_fuse(regs(oprs[3]))
    else: kw["vdst"]=_fuse(regs(x))
  elif group is RDNA3Ops.DS:
    kw = dict(addr=_immorreg(oprs[0]), offset1=_immorreg(oprs[1]))
    if reg(x) is None: kw["data0"]=_fuse(regs(oprs[3]))
    else: kw["vdst"]=_fuse(regs(x))
  elif group is RDNA3Ops.SOPK: args = [dsl.NULL, oprs[0].arg]
  elif group is RDNA3Ops.VOP3SD:
    kw = dict(vdst=_fuse(regs(x)))
    for i,u in enumerate(oprs): kw[f"src{i}"]=_immorreg(u)
  elif group in [RDNA3Ops.VOP3, RDNA3Ops.VOP2, RDNA3Ops.VOP1, RDNA3Ops.VOPC, RDNA3Ops.SOP1, RDNA3Ops.SOP2, RDNA3Ops.VOP3_SDST]: # alu
    args = [_fuse(regs(x))] + [_immorreg(u) for u in oprs]
  elif group is RDNA3Ops.SOPP: args = (0,)
  else: raise NotImplementedError(f"instruction type encoding unsupported, ins group={group}, opcode={opc}")
  
  #print("encoding", opc)
  ret = enc(**kw) if kw is not None else enc(*args)
  return x.replace(arg=ret)

# https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/AMDGPU/SIInsertWaitcnts.cpp#L250
from enum import Enum, auto
class CounterType(Enum):
  DS_CNT = auto(); LOAD_CNT = auto(); STORE_CNT = auto()

def _counter(x:UOp):
  if x.arg.func in [RDNA3Ops.DS, RDNA3Ops.SMEM]: return CounterType.DS_CNT
  elif reg(x) is None: return CounterType.STORE_CNT
  else: return CounterType.LOAD_CNT

@dataclass
class RDNA3LinearCtx:
  loop_label: dict[UOp, str] = field(default_factory=dict)

class RDNA3Renderer(ISARenderer):
  device = "AMD"
  pre_isel_matcher = pre_isel_matcher
  isel_matcher = isel_matcher
  post_regalloc_matcher = post_regalloc_matcher
  code_for_op = {x: lambda: None for x in (Ops.SQRT, Ops.LOG2, Ops.EXP2, Ops.SUB, Ops.RECIPROCAL, Ops.SIN, Ops.TRUNC, Ops.CMPLT, Ops.CMPEQ, Ops.CMPNE, Ops.XOR)}
  post_regalloc_ctx = RDNA3LinearCtx()
  def __init__(self, target:Target):
    super().__init__(target)

  def is_two_address(self, x:UOp) -> bool:
    if x.op is not Ops.INS: return False
    return x.arg.func in [RDNA3Ops.VOP1] and x.src[0].op is Ops.BUFFER and not isinstance(reg(x), Register)

  def spill_pointer(self) -> UOp: return spill_ptr
  # load spilled value into lds
  def spill(self, disp:UOp, x:UOp) -> UOp: # disp is the byte offset into spill space
    ret = isel_matcher.rewrite(self.spill_pointer().index(const(dtypes.uint32, disp//4)).store(x))
    assert ret is not None
    return ret

  # this is going to have to handle multiple regs
  def fill(self, disp:UOp, x:UOp, reg:Register) -> UOp:
    val = isel_matcher.rewrite(self.spill_pointer().index(const(dtypes.uint32, disp//4)).load())
    # assume reg is vgpr?
    return x

  def asm(self, prg:UOp, lin:UOp) -> bytes:
    # insert waitcnts
    bld_cntstate: dict[CounterType, int] = {CounterType.DS_CNT:0, CounterType.LOAD_CNT:0, CounterType.STORE_CNT:0}
    fill_cntstate: dict[CounterType, int] = {CounterType.DS_CNT:0, CounterType.LOAD_CNT:0, CounterType.STORE_CNT:0}
    # maps op that consumes sync dependent register to cnt requirement + pc from which this cnt is required
    tosync: dict[Register, tuple[CounterType, list[tuple[int, int]]]] = {}
    nuops = []
    waitins = { CounterType.DS_CNT:RDNA3Ops.s_waitcnt_lgkmcnt, CounterType.LOAD_CNT:RDNA3Ops.s_waitcnt_vmcnt, CounterType.STORE_CNT:RDNA3Ops.s_waitcnt_vscnt }
    for i, u in enumerate(lin.src):
      if u.arg.func not in [RDNA3Ops.GLOBAL, RDNA3Ops.SMEM, RDNA3Ops.DS]: continue
      ctp = _counter(u)
      if reg(u) is not None:
        for r in regs(u): tosync.setdefault(r,(ctp,[]))[1].append((i,bld_cntstate[ctp]))
      bld_cntstate[ctp] += 1

    # NOTE: broken
    for i, u in enumerate(lin.src):
      if u.arg.func in [RDNA3Ops.GLOBAL, RDNA3Ops.SMEM, RDNA3Ops.DS]: fill_cntstate[_counter(u)] += 1
      deps = [r for s in u.src for r in regs(s) if r in tosync]
      waits = {}
      for r in deps:
        tp, pts = tosync[r]
        cnt = next((n for j,n in reversed(pts) if i > j), None)
        if (cnt is not None) and fill_cntstate[tp] > cnt:
          fill_cntstate[tp] = waits[tp] = min(waits.setdefault(tp, float('inf')), cnt)
      nuops.extend([UOp(Ops.INS, arg=waitins[tp], src=(const(dtypes.uint16,n),)) for tp,n in waits.items()])
      nuops.append(u)

    # labels + encode
    pc = 0
    targets: dict[str, int] = {}
    _asm: list[tuple[UOp,int]] = []
    for u in nuops:
      if u.arg is RDNA3Ops.s_nop:
        if isinstance(u.tag, str):
          targets[u.tag] = pc
        continue
      l = encode(self,u)
      pc += l.arg.size()
      _asm.append((l,pc))

    # if (cond) PC = PC + (SIMM16 *4) +4
    def _reslv(u:UOp,upc:int):
      if not isinstance(u.tag, str): return u
      simm = (targets[u.tag] - upc) // 4
      return u.replace(arg=RDNA3Ops.SOPP(u.arg.op, simm))
    lin = lin.replace(src=tuple([_reslv(u,p) for u,p in _asm]))

    #print(prg.arg)
    #for u in lin.src: print(u.arg)
     
    from tinygrad.renderer.amd.elf import assemble_linear
    return assemble_linear(prg, lin, self.target.arch)
