# mypy: disable-error-code="empty-body"
import ctypes
from typing import Literal, TypeAlias
from tinygrad.runtime.support.c import _IO, _IOW, _IOR, _IOWR
from tinygrad.runtime.support import c
dll = c.DLL('iokit', 'IOKit')
class struct_IONotificationPort(c.Struct): pass
IONotificationPortRef: TypeAlias = ctypes.POINTER(struct_IONotificationPort)
IOServiceMatchingCallback: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_uint32)
IOServiceInterestCallback: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_uint32, ctypes.c_uint32, ctypes.c_void_p)
mach_port_t: TypeAlias = ctypes.c_uint32
try: kIOMainPortDefault = mach_port_t.in_dll(dll, 'kIOMainPortDefault') # type: ignore
except (ValueError,AttributeError): pass
kern_return_t: TypeAlias = ctypes.c_int32
@dll.bind
def IOMainPort(bootstrapPort:mach_port_t, mainPort:ctypes.POINTER(mach_port_t)) -> kern_return_t: ...
try: kIOMasterPortDefault = mach_port_t.in_dll(dll, 'kIOMasterPortDefault') # type: ignore
except (ValueError,AttributeError): pass
@dll.bind
def IOMasterPort(bootstrapPort:mach_port_t, mainPort:ctypes.POINTER(mach_port_t)) -> kern_return_t: ...
@dll.bind
def IONotificationPortCreate(mainPort:mach_port_t) -> IONotificationPortRef: ...
@dll.bind
def IONotificationPortDestroy(notify:IONotificationPortRef) -> None: ...
class struct___CFRunLoopSource(c.Struct): pass
CFRunLoopSourceRef: TypeAlias = ctypes.POINTER(struct___CFRunLoopSource)
@dll.bind
def IONotificationPortGetRunLoopSource(notify:IONotificationPortRef) -> CFRunLoopSourceRef: ...
@dll.bind
def IONotificationPortGetMachPort(notify:IONotificationPortRef) -> mach_port_t: ...
@dll.bind
def IONotificationPortSetImportanceReceiver(notify:IONotificationPortRef) -> kern_return_t: ...
class struct_dispatch_queue_s(c.Struct): pass
dispatch_queue_t: TypeAlias = ctypes.POINTER(struct_dispatch_queue_s)
@dll.bind
def IONotificationPortSetDispatchQueue(notify:IONotificationPortRef, queue:dispatch_queue_t) -> None: ...
@c.record
class mach_msg_header_t(c.Struct):
  SIZE = 24
  msgh_bits: 'int'
  msgh_size: 'int'
  msgh_remote_port: 'int'
  msgh_local_port: 'int'
  msgh_voucher_port: 'int'
  msgh_id: 'int'
mach_msg_bits_t: TypeAlias = ctypes.c_uint32
mach_msg_size_t: TypeAlias = ctypes.c_uint32
mach_port_name_t: TypeAlias = ctypes.c_uint32
mach_msg_id_t: TypeAlias = ctypes.c_int32
mach_msg_header_t.register_fields([('msgh_bits', mach_msg_bits_t, 0), ('msgh_size', mach_msg_size_t, 4), ('msgh_remote_port', mach_port_t, 8), ('msgh_local_port', mach_port_t, 12), ('msgh_voucher_port', mach_port_name_t, 16), ('msgh_id', mach_msg_id_t, 20)])
@dll.bind
def IODispatchCalloutFromMessage(unused:ctypes.c_void_p, msg:ctypes.POINTER(mach_msg_header_t), reference:ctypes.c_void_p) -> None: ...
uint32_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IOCreateReceivePort(msgType:uint32_t, recvPort:ctypes.POINTER(mach_port_t)) -> kern_return_t: ...
io_object_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IOObjectRelease(object:io_object_t) -> kern_return_t: ...
@dll.bind
def IOObjectRetain(object:io_object_t) -> kern_return_t: ...
io_name_t: TypeAlias = (ctypes.c_char * 128)
@dll.bind
def IOObjectGetClass(object:io_object_t, className:io_name_t) -> kern_return_t: ...
class struct___CFString(c.Struct): pass
CFStringRef: TypeAlias = ctypes.POINTER(struct___CFString)
@dll.bind
def IOObjectCopyClass(object:io_object_t) -> CFStringRef: ...
@dll.bind
def IOObjectCopySuperclassForClass(classname:CFStringRef) -> CFStringRef: ...
@dll.bind
def IOObjectCopyBundleIdentifierForClass(classname:CFStringRef) -> CFStringRef: ...
boolean_t: TypeAlias = ctypes.c_int32
@dll.bind
def IOObjectConformsTo(object:io_object_t, className:io_name_t) -> boolean_t: ...
@dll.bind
def IOObjectIsEqualTo(object:io_object_t, anObject:io_object_t) -> boolean_t: ...
@dll.bind
def IOObjectGetKernelRetainCount(object:io_object_t) -> uint32_t: ...
@dll.bind
def IOObjectGetUserRetainCount(object:io_object_t) -> uint32_t: ...
@dll.bind
def IOObjectGetRetainCount(object:io_object_t) -> uint32_t: ...
io_iterator_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IOIteratorNext(iterator:io_iterator_t) -> io_object_t: ...
@dll.bind
def IOIteratorReset(iterator:io_iterator_t) -> None: ...
@dll.bind
def IOIteratorIsValid(iterator:io_iterator_t) -> boolean_t: ...
class struct___CFDictionary(c.Struct): pass
CFDictionaryRef: TypeAlias = ctypes.POINTER(struct___CFDictionary)
io_service_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IOServiceGetMatchingService(mainPort:mach_port_t, matching:CFDictionaryRef) -> io_service_t: ...
@dll.bind
def IOServiceGetMatchingServices(mainPort:mach_port_t, matching:CFDictionaryRef, existing:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
uintptr_t: TypeAlias = ctypes.c_uint64
@dll.bind
def IOServiceAddNotification(mainPort:mach_port_t, notificationType:io_name_t, matching:CFDictionaryRef, wakePort:mach_port_t, reference:uintptr_t, notification:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IOServiceAddMatchingNotification(notifyPort:IONotificationPortRef, notificationType:io_name_t, matching:CFDictionaryRef, callback:IOServiceMatchingCallback, refCon:ctypes.c_void_p, notification:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IOServiceAddInterestNotification(notifyPort:IONotificationPortRef, service:io_service_t, interestType:io_name_t, callback:IOServiceInterestCallback, refCon:ctypes.c_void_p, notification:ctypes.POINTER(io_object_t)) -> kern_return_t: ...
@dll.bind
def IOServiceMatchPropertyTable(service:io_service_t, matching:CFDictionaryRef, matches:ctypes.POINTER(boolean_t)) -> kern_return_t: ...
@dll.bind
def IOServiceGetBusyState(service:io_service_t, busyState:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
@c.record
class struct_mach_timespec(c.Struct):
  SIZE = 8
  tv_sec: 'int'
  tv_nsec: 'int'
mach_timespec_t: TypeAlias = struct_mach_timespec
clock_res_t: TypeAlias = ctypes.c_int32
struct_mach_timespec.register_fields([('tv_sec', ctypes.c_uint32, 0), ('tv_nsec', clock_res_t, 4)])
@dll.bind
def IOServiceWaitQuiet(service:io_service_t, waitTime:ctypes.POINTER(mach_timespec_t)) -> kern_return_t: ...
@dll.bind
def IOKitGetBusyState(mainPort:mach_port_t, busyState:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
IOOptionBits: TypeAlias = ctypes.c_uint32
@dll.bind
def IOKitWaitQuietWithOptions(mainPort:mach_port_t, waitTime:ctypes.POINTER(mach_timespec_t), options:IOOptionBits) -> kern_return_t: ...
@dll.bind
def IOKitWaitQuiet(mainPort:mach_port_t, waitTime:ctypes.POINTER(mach_timespec_t)) -> kern_return_t: ...
task_port_t: TypeAlias = ctypes.c_uint32
io_connect_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IOServiceOpen(service:io_service_t, owningTask:task_port_t, type:uint32_t, connect:ctypes.POINTER(io_connect_t)) -> kern_return_t: ...
@dll.bind
def IOServiceRequestProbe(service:io_service_t, options:uint32_t) -> kern_return_t: ...
_anonenum0: dict[int, str] = {(kIOServiceInteractionAllowed:=1): 'kIOServiceInteractionAllowed'}
@dll.bind
def IOServiceAuthorize(service:io_service_t, options:uint32_t) -> kern_return_t: ...
@dll.bind
def IOServiceOpenAsFileDescriptor(service:io_service_t, oflag:ctypes.c_int32) -> ctypes.c_int32: ...
@dll.bind
def IOServiceClose(connect:io_connect_t) -> kern_return_t: ...
@dll.bind
def IOConnectAddRef(connect:io_connect_t) -> kern_return_t: ...
@dll.bind
def IOConnectRelease(connect:io_connect_t) -> kern_return_t: ...
@dll.bind
def IOConnectGetService(connect:io_connect_t, service:ctypes.POINTER(io_service_t)) -> kern_return_t: ...
@dll.bind
def IOConnectSetNotificationPort(connect:io_connect_t, type:uint32_t, port:mach_port_t, reference:uintptr_t) -> kern_return_t: ...
mach_vm_address_t: TypeAlias = ctypes.c_uint64
mach_vm_size_t: TypeAlias = ctypes.c_uint64
@dll.bind
def IOConnectMapMemory(connect:io_connect_t, memoryType:uint32_t, intoTask:task_port_t, atAddress:ctypes.POINTER(mach_vm_address_t), ofSize:ctypes.POINTER(mach_vm_size_t), options:IOOptionBits) -> kern_return_t: ...
@dll.bind
def IOConnectMapMemory64(connect:io_connect_t, memoryType:uint32_t, intoTask:task_port_t, atAddress:ctypes.POINTER(mach_vm_address_t), ofSize:ctypes.POINTER(mach_vm_size_t), options:IOOptionBits) -> kern_return_t: ...
@dll.bind
def IOConnectUnmapMemory(connect:io_connect_t, memoryType:uint32_t, fromTask:task_port_t, atAddress:mach_vm_address_t) -> kern_return_t: ...
@dll.bind
def IOConnectUnmapMemory64(connect:io_connect_t, memoryType:uint32_t, fromTask:task_port_t, atAddress:mach_vm_address_t) -> kern_return_t: ...
CFTypeRef: TypeAlias = ctypes.c_void_p
@dll.bind
def IOConnectSetCFProperties(connect:io_connect_t, properties:CFTypeRef) -> kern_return_t: ...
@dll.bind
def IOConnectSetCFProperty(connect:io_connect_t, propertyName:CFStringRef, property:CFTypeRef) -> kern_return_t: ...
uint64_t: TypeAlias = ctypes.c_uint64
size_t: TypeAlias = ctypes.c_uint64
@dll.bind
def IOConnectCallMethod(connection:mach_port_t, selector:uint32_t, input:ctypes.POINTER(uint64_t), inputCnt:uint32_t, inputStruct:ctypes.c_void_p, inputStructCnt:size_t, output:ctypes.POINTER(uint64_t), outputCnt:ctypes.POINTER(uint32_t), outputStruct:ctypes.c_void_p, outputStructCnt:ctypes.POINTER(size_t)) -> kern_return_t: ...
@dll.bind
def IOConnectCallAsyncMethod(connection:mach_port_t, selector:uint32_t, wake_port:mach_port_t, reference:ctypes.POINTER(uint64_t), referenceCnt:uint32_t, input:ctypes.POINTER(uint64_t), inputCnt:uint32_t, inputStruct:ctypes.c_void_p, inputStructCnt:size_t, output:ctypes.POINTER(uint64_t), outputCnt:ctypes.POINTER(uint32_t), outputStruct:ctypes.c_void_p, outputStructCnt:ctypes.POINTER(size_t)) -> kern_return_t: ...
@dll.bind
def IOConnectCallStructMethod(connection:mach_port_t, selector:uint32_t, inputStruct:ctypes.c_void_p, inputStructCnt:size_t, outputStruct:ctypes.c_void_p, outputStructCnt:ctypes.POINTER(size_t)) -> kern_return_t: ...
@dll.bind
def IOConnectCallAsyncStructMethod(connection:mach_port_t, selector:uint32_t, wake_port:mach_port_t, reference:ctypes.POINTER(uint64_t), referenceCnt:uint32_t, inputStruct:ctypes.c_void_p, inputStructCnt:size_t, outputStruct:ctypes.c_void_p, outputStructCnt:ctypes.POINTER(size_t)) -> kern_return_t: ...
@dll.bind
def IOConnectCallScalarMethod(connection:mach_port_t, selector:uint32_t, input:ctypes.POINTER(uint64_t), inputCnt:uint32_t, output:ctypes.POINTER(uint64_t), outputCnt:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
@dll.bind
def IOConnectCallAsyncScalarMethod(connection:mach_port_t, selector:uint32_t, wake_port:mach_port_t, reference:ctypes.POINTER(uint64_t), referenceCnt:uint32_t, input:ctypes.POINTER(uint64_t), inputCnt:uint32_t, output:ctypes.POINTER(uint64_t), outputCnt:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
@dll.bind
def IOConnectTrap0(connect:io_connect_t, index:uint32_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap1(connect:io_connect_t, index:uint32_t, p1:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap2(connect:io_connect_t, index:uint32_t, p1:uintptr_t, p2:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap3(connect:io_connect_t, index:uint32_t, p1:uintptr_t, p2:uintptr_t, p3:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap4(connect:io_connect_t, index:uint32_t, p1:uintptr_t, p2:uintptr_t, p3:uintptr_t, p4:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap5(connect:io_connect_t, index:uint32_t, p1:uintptr_t, p2:uintptr_t, p3:uintptr_t, p4:uintptr_t, p5:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectTrap6(connect:io_connect_t, index:uint32_t, p1:uintptr_t, p2:uintptr_t, p3:uintptr_t, p4:uintptr_t, p5:uintptr_t, p6:uintptr_t) -> kern_return_t: ...
@dll.bind
def IOConnectAddClient(connect:io_connect_t, client:io_connect_t) -> kern_return_t: ...
io_registry_entry_t: TypeAlias = ctypes.c_uint32
@dll.bind
def IORegistryGetRootEntry(mainPort:mach_port_t) -> io_registry_entry_t: ...
io_string_t: TypeAlias = (ctypes.c_char * 512)
@dll.bind
def IORegistryEntryFromPath(mainPort:mach_port_t, path:io_string_t) -> io_registry_entry_t: ...
@dll.bind
def IORegistryEntryCopyFromPath(mainPort:mach_port_t, path:CFStringRef) -> io_registry_entry_t: ...
_anonenum1: dict[int, str] = {(kIORegistryIterateRecursively:=1): 'kIORegistryIterateRecursively', (kIORegistryIterateParents:=2): 'kIORegistryIterateParents'}
@dll.bind
def IORegistryCreateIterator(mainPort:mach_port_t, plane:io_name_t, options:IOOptionBits, iterator:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntryCreateIterator(entry:io_registry_entry_t, plane:io_name_t, options:IOOptionBits, iterator:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IORegistryIteratorEnterEntry(iterator:io_iterator_t) -> kern_return_t: ...
@dll.bind
def IORegistryIteratorExitEntry(iterator:io_iterator_t) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetName(entry:io_registry_entry_t, name:io_name_t) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetNameInPlane(entry:io_registry_entry_t, plane:io_name_t, name:io_name_t) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetLocationInPlane(entry:io_registry_entry_t, plane:io_name_t, location:io_name_t) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetPath(entry:io_registry_entry_t, plane:io_name_t, path:io_string_t) -> kern_return_t: ...
@dll.bind
def IORegistryEntryCopyPath(entry:io_registry_entry_t, plane:io_name_t) -> CFStringRef: ...
@dll.bind
def IORegistryEntryGetRegistryEntryID(entry:io_registry_entry_t, entryID:ctypes.POINTER(uint64_t)) -> kern_return_t: ...
CFMutableDictionaryRef: TypeAlias = ctypes.POINTER(struct___CFDictionary)
class struct___CFAllocator(c.Struct): pass
CFAllocatorRef: TypeAlias = ctypes.POINTER(struct___CFAllocator)
@dll.bind
def IORegistryEntryCreateCFProperties(entry:io_registry_entry_t, properties:ctypes.POINTER(CFMutableDictionaryRef), allocator:CFAllocatorRef, options:IOOptionBits) -> kern_return_t: ...
@dll.bind
def IORegistryEntryCreateCFProperty(entry:io_registry_entry_t, key:CFStringRef, allocator:CFAllocatorRef, options:IOOptionBits) -> CFTypeRef: ...
@dll.bind
def IORegistryEntrySearchCFProperty(entry:io_registry_entry_t, plane:io_name_t, key:CFStringRef, allocator:CFAllocatorRef, options:IOOptionBits) -> CFTypeRef: ...
io_struct_inband_t: TypeAlias = (ctypes.c_char * 4096)
@dll.bind
def IORegistryEntryGetProperty(entry:io_registry_entry_t, propertyName:io_name_t, buffer:io_struct_inband_t, size:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntrySetCFProperties(entry:io_registry_entry_t, properties:CFTypeRef) -> kern_return_t: ...
@dll.bind
def IORegistryEntrySetCFProperty(entry:io_registry_entry_t, propertyName:CFStringRef, property:CFTypeRef) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetChildIterator(entry:io_registry_entry_t, plane:io_name_t, iterator:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetChildEntry(entry:io_registry_entry_t, plane:io_name_t, child:ctypes.POINTER(io_registry_entry_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetParentIterator(entry:io_registry_entry_t, plane:io_name_t, iterator:ctypes.POINTER(io_iterator_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntryGetParentEntry(entry:io_registry_entry_t, plane:io_name_t, parent:ctypes.POINTER(io_registry_entry_t)) -> kern_return_t: ...
@dll.bind
def IORegistryEntryInPlane(entry:io_registry_entry_t, plane:io_name_t) -> boolean_t: ...
@dll.bind
def IOServiceMatching(name:ctypes.POINTER(ctypes.c_char)) -> CFMutableDictionaryRef: ...
@dll.bind
def IOServiceNameMatching(name:ctypes.POINTER(ctypes.c_char)) -> CFMutableDictionaryRef: ...
@dll.bind
def IOBSDNameMatching(mainPort:mach_port_t, options:uint32_t, bsdName:ctypes.POINTER(ctypes.c_char)) -> CFMutableDictionaryRef: ...
@dll.bind
def IOOpenFirmwarePathMatching(mainPort:mach_port_t, options:uint32_t, path:ctypes.POINTER(ctypes.c_char)) -> CFMutableDictionaryRef: ...
@dll.bind
def IORegistryEntryIDMatching(entryID:uint64_t) -> CFMutableDictionaryRef: ...
@dll.bind
def IOServiceOFPathToBSDName(mainPort:mach_port_t, openFirmwarePath:io_name_t, bsdName:io_name_t) -> kern_return_t: ...
IOAsyncCallback0: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int32)
IOAsyncCallback1: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int32, ctypes.c_void_p)
IOAsyncCallback2: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int32, ctypes.c_void_p, ctypes.c_void_p)
IOAsyncCallback: TypeAlias = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int32, ctypes.POINTER(ctypes.c_void_p), ctypes.c_uint32)
vm_size_t: TypeAlias = ctypes.c_uint64
@dll.bind
def OSGetNotificationFromMessage(msg:ctypes.POINTER(mach_msg_header_t), index:uint32_t, type:ctypes.POINTER(uint32_t), reference:ctypes.POINTER(uintptr_t), content:ctypes.POINTER(ctypes.c_void_p), size:ctypes.POINTER(vm_size_t)) -> kern_return_t: ...
@dll.bind
def IOCatalogueSendData(mainPort:mach_port_t, flag:uint32_t, buffer:ctypes.POINTER(ctypes.c_char), size:uint32_t) -> kern_return_t: ...
@dll.bind
def IOCatalogueTerminate(mainPort:mach_port_t, flag:uint32_t, description:io_name_t) -> kern_return_t: ...
@dll.bind
def IOCatalogueGetData(mainPort:mach_port_t, flag:uint32_t, buffer:ctypes.POINTER(ctypes.POINTER(ctypes.c_char)), size:ctypes.POINTER(uint32_t)) -> kern_return_t: ...
@dll.bind
def IOCatalogueModuleLoaded(mainPort:mach_port_t, name:io_name_t) -> kern_return_t: ...
@dll.bind
def IOCatalogueReset(mainPort:mach_port_t, flag:uint32_t) -> kern_return_t: ...
