from __future__ import annotations
import ctypes
from typing import Annotated, Literal
from tinygrad.runtime.support.c import DLL, record, Array, POINTER, CFUNCTYPE, CEnum, _IO, _IOW, _IOR, _IOWR, init_records
import sysconfig
dll = DLL('nvrtc', 'nvrtc', f'/usr/local/cuda/targets/{sysconfig.get_config_vars().get("MULTIARCH", "").rsplit("-", 1)[0]}/lib')
nvrtcResult = CEnum(Annotated[int, ctypes.c_uint32])
NVRTC_SUCCESS = nvrtcResult.define('NVRTC_SUCCESS', 0)
NVRTC_ERROR_OUT_OF_MEMORY = nvrtcResult.define('NVRTC_ERROR_OUT_OF_MEMORY', 1)
NVRTC_ERROR_PROGRAM_CREATION_FAILURE = nvrtcResult.define('NVRTC_ERROR_PROGRAM_CREATION_FAILURE', 2)
NVRTC_ERROR_INVALID_INPUT = nvrtcResult.define('NVRTC_ERROR_INVALID_INPUT', 3)
NVRTC_ERROR_INVALID_PROGRAM = nvrtcResult.define('NVRTC_ERROR_INVALID_PROGRAM', 4)
NVRTC_ERROR_INVALID_OPTION = nvrtcResult.define('NVRTC_ERROR_INVALID_OPTION', 5)
NVRTC_ERROR_COMPILATION = nvrtcResult.define('NVRTC_ERROR_COMPILATION', 6)
NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = nvrtcResult.define('NVRTC_ERROR_BUILTIN_OPERATION_FAILURE', 7)
NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = nvrtcResult.define('NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION', 8)
NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = nvrtcResult.define('NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION', 9)
NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = nvrtcResult.define('NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID', 10)
NVRTC_ERROR_INTERNAL_ERROR = nvrtcResult.define('NVRTC_ERROR_INTERNAL_ERROR', 11)

@dll.bind
def nvrtcGetErrorString(result:nvrtcResult) -> POINTER(Annotated[bytes, ctypes.c_char]): ...
@dll.bind
def nvrtcVersion(major:POINTER(Annotated[int, ctypes.c_int32]), minor:POINTER(Annotated[int, ctypes.c_int32])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetNumSupportedArchs(numArchs:POINTER(Annotated[int, ctypes.c_int32])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetSupportedArchs(supportedArchs:POINTER(Annotated[int, ctypes.c_int32])) -> nvrtcResult: ...
class struct__nvrtcProgram(ctypes.Structure): pass
nvrtcProgram = POINTER(struct__nvrtcProgram)
@dll.bind
def nvrtcCreateProgram(prog:POINTER(nvrtcProgram), src:POINTER(Annotated[bytes, ctypes.c_char]), name:POINTER(Annotated[bytes, ctypes.c_char]), numHeaders:Annotated[int, ctypes.c_int32], headers:POINTER(POINTER(Annotated[bytes, ctypes.c_char])), includeNames:POINTER(POINTER(Annotated[bytes, ctypes.c_char]))) -> nvrtcResult: ...
@dll.bind
def nvrtcDestroyProgram(prog:POINTER(nvrtcProgram)) -> nvrtcResult: ...
@dll.bind
def nvrtcCompileProgram(prog:nvrtcProgram, numOptions:Annotated[int, ctypes.c_int32], options:POINTER(POINTER(Annotated[bytes, ctypes.c_char]))) -> nvrtcResult: ...
size_t = Annotated[int, ctypes.c_uint64]
@dll.bind
def nvrtcGetPTXSize(prog:nvrtcProgram, ptxSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetPTX(prog:nvrtcProgram, ptx:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetCUBINSize(prog:nvrtcProgram, cubinSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetCUBIN(prog:nvrtcProgram, cubin:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetNVVMSize(prog:nvrtcProgram, nvvmSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetNVVM(prog:nvrtcProgram, nvvm:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetLTOIRSize(prog:nvrtcProgram, LTOIRSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetLTOIR(prog:nvrtcProgram, LTOIR:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetOptiXIRSize(prog:nvrtcProgram, optixirSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetOptiXIR(prog:nvrtcProgram, optixir:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetProgramLogSize(prog:nvrtcProgram, logSizeRet:POINTER(size_t)) -> nvrtcResult: ...
@dll.bind
def nvrtcGetProgramLog(prog:nvrtcProgram, log:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcAddNameExpression(prog:nvrtcProgram, name_expression:POINTER(Annotated[bytes, ctypes.c_char])) -> nvrtcResult: ...
@dll.bind
def nvrtcGetLoweredName(prog:nvrtcProgram, name_expression:POINTER(Annotated[bytes, ctypes.c_char]), lowered_name:POINTER(POINTER(Annotated[bytes, ctypes.c_char]))) -> nvrtcResult: ...
init_records()
__DEPRECATED__ = lambda msg: __attribute__((deprecated(msg)))