# mypy: ignore-errors
import ctypes
from tinygrad.runtime.support.c import Array, DLL, Pointer, Struct, Union, field, CEnum, _IO, _IOW, _IOR, _IOWR
import sysconfig
dll = DLL('nvrtc', 'nvrtc', f'/usr/local/cuda/targets/{sysconfig.get_config_vars().get("MULTIARCH", "").rsplit("-", 1)[0]}/lib')
nvrtcResult = CEnum(ctypes.c_uint32)
NVRTC_SUCCESS = nvrtcResult.define('NVRTC_SUCCESS', 0)
NVRTC_ERROR_OUT_OF_MEMORY = nvrtcResult.define('NVRTC_ERROR_OUT_OF_MEMORY', 1)
NVRTC_ERROR_PROGRAM_CREATION_FAILURE = nvrtcResult.define('NVRTC_ERROR_PROGRAM_CREATION_FAILURE', 2)
NVRTC_ERROR_INVALID_INPUT = nvrtcResult.define('NVRTC_ERROR_INVALID_INPUT', 3)
NVRTC_ERROR_INVALID_PROGRAM = nvrtcResult.define('NVRTC_ERROR_INVALID_PROGRAM', 4)
NVRTC_ERROR_INVALID_OPTION = nvrtcResult.define('NVRTC_ERROR_INVALID_OPTION', 5)
NVRTC_ERROR_COMPILATION = nvrtcResult.define('NVRTC_ERROR_COMPILATION', 6)
NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = nvrtcResult.define('NVRTC_ERROR_BUILTIN_OPERATION_FAILURE', 7)
NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = nvrtcResult.define('NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION', 8)
NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = nvrtcResult.define('NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION', 9)
NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = nvrtcResult.define('NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID', 10)
NVRTC_ERROR_INTERNAL_ERROR = nvrtcResult.define('NVRTC_ERROR_INTERNAL_ERROR', 11)

@dll.bind((nvrtcResult,), Pointer(ctypes.c_char))
def nvrtcGetErrorString(result): ...
@dll.bind((Pointer(ctypes.c_int32), Pointer(ctypes.c_int32),), nvrtcResult)
def nvrtcVersion(major, minor): ...
@dll.bind((Pointer(ctypes.c_int32),), nvrtcResult)
def nvrtcGetNumSupportedArchs(numArchs): ...
@dll.bind((Pointer(ctypes.c_int32),), nvrtcResult)
def nvrtcGetSupportedArchs(supportedArchs): ...
class struct__nvrtcProgram(Struct): pass
nvrtcProgram = Pointer(struct__nvrtcProgram)
@dll.bind((Pointer(nvrtcProgram), Pointer(ctypes.c_char), Pointer(ctypes.c_char), ctypes.c_int32, Pointer(Pointer(ctypes.c_char)), Pointer(Pointer(ctypes.c_char)),), nvrtcResult)
def nvrtcCreateProgram(prog, src, name, numHeaders, headers, includeNames): ...
@dll.bind((Pointer(nvrtcProgram),), nvrtcResult)
def nvrtcDestroyProgram(prog): ...
@dll.bind((nvrtcProgram, ctypes.c_int32, Pointer(Pointer(ctypes.c_char)),), nvrtcResult)
def nvrtcCompileProgram(prog, numOptions, options): ...
size_t = ctypes.c_uint64
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetPTXSize(prog, ptxSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetPTX(prog, ptx): ...
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetCUBINSize(prog, cubinSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetCUBIN(prog, cubin): ...
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetNVVMSize(prog, nvvmSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetNVVM(prog, nvvm): ...
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetLTOIRSize(prog, LTOIRSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetLTOIR(prog, LTOIR): ...
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetOptiXIRSize(prog, optixirSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetOptiXIR(prog, optixir): ...
@dll.bind((nvrtcProgram, Pointer(size_t),), nvrtcResult)
def nvrtcGetProgramLogSize(prog, logSizeRet): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcGetProgramLog(prog, log): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char),), nvrtcResult)
def nvrtcAddNameExpression(prog, name_expression): ...
@dll.bind((nvrtcProgram, Pointer(ctypes.c_char), Pointer(Pointer(ctypes.c_char)),), nvrtcResult)
def nvrtcGetLoweredName(prog, name_expression, lowered_name): ...
__DEPRECATED__ = lambda msg: __attribute__((deprecated(msg)))