# mypy: disable-error-code="empty-body"
from __future__ import annotations
import ctypes
from typing import Literal, TypeAlias
from tinygrad.runtime.support.c import _IO, _IOW, _IOR, _IOWR
from tinygrad.runtime.support import c
import sysconfig
dll = c.DLL('nvrtc', 'nvrtc', [f'/{pre}/cuda/targets/{sysconfig.get_config_vars().get("MULTIARCH", "").rsplit("-", 1)[0]}/lib' for pre in ['opt', 'usr/local']])
nvrtcResult: dict[int, str] = {(NVRTC_SUCCESS:=0): 'NVRTC_SUCCESS', (NVRTC_ERROR_OUT_OF_MEMORY:=1): 'NVRTC_ERROR_OUT_OF_MEMORY', (NVRTC_ERROR_PROGRAM_CREATION_FAILURE:=2): 'NVRTC_ERROR_PROGRAM_CREATION_FAILURE', (NVRTC_ERROR_INVALID_INPUT:=3): 'NVRTC_ERROR_INVALID_INPUT', (NVRTC_ERROR_INVALID_PROGRAM:=4): 'NVRTC_ERROR_INVALID_PROGRAM', (NVRTC_ERROR_INVALID_OPTION:=5): 'NVRTC_ERROR_INVALID_OPTION', (NVRTC_ERROR_COMPILATION:=6): 'NVRTC_ERROR_COMPILATION', (NVRTC_ERROR_BUILTIN_OPERATION_FAILURE:=7): 'NVRTC_ERROR_BUILTIN_OPERATION_FAILURE', (NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION:=8): 'NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION', (NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION:=9): 'NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION', (NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID:=10): 'NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID', (NVRTC_ERROR_INTERNAL_ERROR:=11): 'NVRTC_ERROR_INTERNAL_ERROR'}
@dll.bind(ctypes.POINTER(ctypes.c_char), ctypes.c_uint32)
def nvrtcGetErrorString(result:ctypes.c_uint32) -> ctypes._Pointer[ctypes.c_char]: ...
@dll.bind(ctypes.c_uint32, ctypes.POINTER(ctypes.c_int32), ctypes.POINTER(ctypes.c_int32))
def nvrtcVersion(major:ctypes._Pointer[ctypes.c_int32], minor:ctypes._Pointer[ctypes.c_int32]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, ctypes.POINTER(ctypes.c_int32))
def nvrtcGetNumSupportedArchs(numArchs:ctypes._Pointer[ctypes.c_int32]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, ctypes.POINTER(ctypes.c_int32))
def nvrtcGetSupportedArchs(supportedArchs:ctypes._Pointer[ctypes.c_int32]) -> ctypes.c_uint32: ...
class struct__nvrtcProgram(c.Struct): pass
nvrtcProgram: TypeAlias = ctypes.POINTER(struct__nvrtcProgram)
@dll.bind(ctypes.c_uint32, ctypes.POINTER(nvrtcProgram), ctypes.POINTER(ctypes.c_char), ctypes.POINTER(ctypes.c_char), ctypes.c_int32, ctypes.POINTER(ctypes.POINTER(ctypes.c_char)), ctypes.POINTER(ctypes.POINTER(ctypes.c_char)))
def nvrtcCreateProgram(prog:ctypes._Pointer[nvrtcProgram], src:ctypes._Pointer[ctypes.c_char], name:ctypes._Pointer[ctypes.c_char], numHeaders:int, headers:ctypes._Pointer[ctypes.POINTER(ctypes.c_char)], includeNames:ctypes._Pointer[ctypes.POINTER(ctypes.c_char)]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, ctypes.POINTER(nvrtcProgram))
def nvrtcDestroyProgram(prog:ctypes._Pointer[nvrtcProgram]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.c_int32, ctypes.POINTER(ctypes.POINTER(ctypes.c_char)))
def nvrtcCompileProgram(prog:nvrtcProgram, numOptions:int, options:ctypes._Pointer[ctypes.POINTER(ctypes.c_char)]) -> ctypes.c_uint32: ...
size_t: TypeAlias = ctypes.c_uint64
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetPTXSize(prog:nvrtcProgram, ptxSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetPTX(prog:nvrtcProgram, ptx:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetCUBINSize(prog:nvrtcProgram, cubinSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetCUBIN(prog:nvrtcProgram, cubin:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetNVVMSize(prog:nvrtcProgram, nvvmSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetNVVM(prog:nvrtcProgram, nvvm:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetLTOIRSize(prog:nvrtcProgram, LTOIRSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetLTOIR(prog:nvrtcProgram, LTOIR:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetOptiXIRSize(prog:nvrtcProgram, optixirSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetOptiXIR(prog:nvrtcProgram, optixir:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(size_t))
def nvrtcGetProgramLogSize(prog:nvrtcProgram, logSizeRet:ctypes._Pointer[size_t]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcGetProgramLog(prog:nvrtcProgram, log:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char))
def nvrtcAddNameExpression(prog:nvrtcProgram, name_expression:ctypes._Pointer[ctypes.c_char]) -> ctypes.c_uint32: ...
@dll.bind(ctypes.c_uint32, nvrtcProgram, ctypes.POINTER(ctypes.c_char), ctypes.POINTER(ctypes.POINTER(ctypes.c_char)))
def nvrtcGetLoweredName(prog:nvrtcProgram, name_expression:ctypes._Pointer[ctypes.c_char], lowered_name:ctypes._Pointer[ctypes.POINTER(ctypes.c_char)]) -> ctypes.c_uint32: ...
__DEPRECATED__ = lambda msg: __attribute__((deprecated(msg))) # type: ignore